### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by aath0** [aath0/AlgorithmsNeuroscience#1]
# Roadmap

**Goal:** develop an open platform with educational resources for algorithmic decision-making in neuroscience

Here is a list of milestones for this project.

### Milestone: List of tutorials for EEG data
> How to apply common algorithms on electroencephalography (EEG) data?

- [ ] Loading and visualization of epoch data 
- [ ] Pre-processing: What are common artifacts? How to reject them? Filtering.
- [ ] Statistics: Contrasts between two conditions at single-electrodes. Permutation statistics.
- [ ] Machine learning: What features can we have? How to implement cross-validation?
- [ ] Machine learning: Common algorithms: LDA / Logistic Regression
- [ ] Machine learning: How to visualize features and classification accuracy
- [ ] Expand to a different dataset / application

### Milestone: Tutorials for signal processing
> e.g. filters, time-frequency transforms

- [ ] Filters...
- [ ] Time-frequency 

### Milestone: Bind everything together
> e.g. through mybinder or Jupyter book
- [ ] Test that MyBinder works
- [ ] Implement everything in Jupyter book
